# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Delete output files"
    lane :clean do
      gradle(task: "clean")
    end

  desc "Run all unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Runs all instrumented tests"
  lane :androidTest do
    clean
    gradle(task: "connectedAndroidTest")
  end

  desc "Build Release APK"
  lane :buildReleaseApk do
    clean
    gradle(
      task: "assembleRelease",
      build_type: "Release"
    )
  end

  desc "Build Release AAB"
    lane :buildReleaseAab do
      clean
      gradle(
        task: "bundle",
        build_type: "Release"
      )
    end

  desc "Build debug and AndroidTest APK for screengrab"
  lane :buildForScreengrab do
    clean
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
    gradle(
      task: "assemble",
      build_type: "AndroidTest"
    )
  end

  desc "Release a new Beta Build to Firebase App Distribution"
  lane :deployToFirebase do
    buildReleaseApk
    firebase_app_distribution(
        app: "",
        groups: "group-two",
        release_notes: "Lots of amazing new features to test out!"
    )
  end

  desc "Release a new version to the Google Play"
  lane :releaseToPlayStore do
    buildReleaseAab
    upload_to_play_store
  end

end
