name: Pull Request Check
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Test
        run: bundle exec fastlane test


